In [67]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import confusion_matrix

In [85]:
traindf = pd.read_csv('train.csv')
testdf = pd.read_csv('valid.csv')

In [86]:
traindf.head()

business_id  cool                 date  funny  \
0  dsvFUqrhytVmKXCW7bKNhA     0  2013-03-10 01:24:07      0   
1  6YrO-hJNof4wsx4f0YQ8yg     0  2014-12-22 17:06:23      0   
2  LtyoPfxpvcF_9e9wMoUi0w     0  2016-04-25 09:55:57      0   
3  QzvLnOqwH6BIY_jCOvzuQQ     0  2017-04-06 04:18:48      0   
4  tPaweigPsXacvQT8daYT4g     0  2017-03-22 15:38:59      0   

                review_id  stars  \
0  58nqw-MdO6EDACPaKDM59Q    5.0   
1  eVeQtMGaB5tdCH0hKJwxKw    3.0   
2  AHMHUbq0eAUOuOPFoeO5iw    4.0   
3  8RDvwneSMsbpmi5UgGq60A    1.0   
4  IboCoxoL0IFtJnsGPHCugg    5.0   

                                                text  useful  \
0  As a student, by back and neck are under const...       0   
1  Stayed here for a football game at University ...       0   
2  Very good salads, generous portions. I either ...       1   
3  The experience I had with this company growing...       0   
4  Easiest furniture purchase, with a great price...       0   

                  user_id  
0  1NImHsg1kc76n_cQyTm0bg  
1  Oi0G3jFm2jtG2W02dZTdEQ  
2  4jbz7cOVuV_Q7v2b3pNrLw  
3  gJgPs0QXE587T9SIR6NCdQ  
4  zp8XLBJmgw55ZTlp5raK7Q

In [184]:
trainpre = traindf[['text','funny','cool','useful','stars']]
testpre = testdf[['text','funny','cool','useful','stars']]
trainhaha = trainpre['text']
testhaha = testpre['text']
trainhehe = trainpre['stars']
testhehe = testpre['stars']

In [185]:
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(trainhaha)
print('vocabulary: ', vectorizer.vocabulary_)
print('idfs: ', vectorizer.idf_)
vector = vectorizer.transform(testhaha)
print('vectors: ', vector.toarray())

vocabulary:  {'as': 6375, 'student': 68796, 'by': 12434, 'back': 7544, 'and': 5125, 'neck': 48634, 'are': 6046, 'under': 74587, 'constant': 17552, 'strain': 68546, 'dr': 23075, 'serrick': 63711, 'manages': 44127, 'to': 72407, 'set': 63782, 'them': 71562, 'straight': 68535, 'every': 25948, 'time': 72156, 'highly': 34449, 'recommend': 58496, 'the': 71531, 'thumper': 71955, 'treatment': 73352, 'for': 28843, 'really': 58213, 'great': 32140, 'muscle': 47989, 'pain': 51856, 'relief': 59178, 'overall': 51377, 'would': 79145, 'say': 62529, 'that': 71514, 'is': 37881, 'very': 76400, 'knowledgeable': 40410, 'empathetic': 24784, 'thorough': 71795, 'recommended': 58501, 'stayed': 68038, 'here': 34259, 'football': 28815, 'game': 30267, 'at': 6679, 'university': 75003, 'of': 50208, 'phoenix': 53819, 'stadium': 67770, 'it': 37975, 'about': 2862, '10mins': 181, 'drive': 23266, 'rooms': 61016, 'average': 7197, 'fine': 27881, 'an': 5050, 'overnight': 51502, 'stay': 68034, 'but': 12303, 'service': 63739,

vectors:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [186]:
train_vectors = vectorizer.fit_transform(trainhaha)
test_vectors = vectorizer.transform(testhaha)

In [ ]:
classifier_linear = svm.SVC(kernel='linear')
classifier_linear.fit(train_vectors, trainhehe)
prediction_train = classifier_linear.predict(train_vectors)
prediction_test = classifier_linear.predict(test_vectors)

In [ ]:
print ('testing dataset accuracy: {}'.format(accuracy_score(testhehe, prediction_test)))
print('\n')
print("Classification report for classifier %s:\n%s\n"
      % (classifier_linear, metrics.classification_report(testhehe, prediction_test)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(testhehe, prediction_test))